using System.Text.Json.Serialization;

namespace WhatsApp2Pipe.Api.Models;

/// <summary>
/// OAuth state parameter sent by Chrome extension or website.
/// This is base64-encoded JSON containing client metadata for CSRF protection
/// and dynamic callback URL generation.
/// </summary>
public class OAuthState
{
    /// <summary>
    /// Client type: "extension" or "web".
    /// Used to determine the callback flow and redirect behavior.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = "extension";

    /// <summary>
    /// Chrome extension ID (e.g., "lfaikknchhcfpllgmgcfjkmojeghlgjd").
    /// Used to construct the callback redirect URL for extension clients.
    /// Optional for web clients.
    /// </summary>
    [JsonPropertyName("extensionId")]
    public string? ExtensionId { get; set; }

    /// <summary>
    /// Nonce for CSRF protection.
    /// Generated by the client to prevent state replay attacks.
    /// </summary>
    [JsonPropertyName("nonce")]
    public string Nonce { get; set; } = string.Empty;

    /// <summary>
    /// Timestamp when state was generated (Unix milliseconds).
    /// Used to validate state freshness and prevent replay attacks.
    /// </summary>
    [JsonPropertyName("timestamp")]
    public long Timestamp { get; set; }
}
