using System.Text.Json.Serialization;

namespace WhatsApp2Pipe.Api.Models;

/// <summary>
/// OAuth state parameter sent by Chrome extension.
/// This is base64-encoded JSON containing extension metadata for CSRF protection
/// and dynamic callback URL generation.
/// </summary>
public class OAuthState
{
    /// <summary>
    /// Chrome extension ID (e.g., "lfaikknchhcfpllgmgcfjkmojeghlgjd").
    /// Used to construct the callback redirect URL.
    /// </summary>
    [JsonPropertyName("extensionId")]
    public string ExtensionId { get; set; } = string.Empty;

    /// <summary>
    /// Nonce for CSRF protection.
    /// Generated by the extension to prevent state replay attacks.
    /// </summary>
    [JsonPropertyName("nonce")]
    public string Nonce { get; set; } = string.Empty;

    /// <summary>
    /// Timestamp when state was generated (Unix milliseconds).
    /// Used to validate state freshness and prevent replay attacks.
    /// </summary>
    [JsonPropertyName("timestamp")]
    public long Timestamp { get; set; }
}
